### ISSUE TITLE
Debian 9 PPA support  

### ISSUE THREAD

**Issue by jebr224** [Yubico/yubikey-manager-qt#189]
Debian 9 support for your PPA would be a great feature. Below is the output when I tried to add the PPA. 

```
j***@td:~$ sudo apt-add-repository ppa:yubico/stable
[sudo] password for john: 
 PPA for stable Yubico software.
 More info: https://launchpad.net/~yubico/+archive/ubuntu/stable
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpzbdm3474/pubring.gpg' created
gpg: /tmp/tmpzbdm3474/trustdb.gpg: trustdb created
gpg: key 43D5C49532CBA1A9: public key "Launchpad PPA for Yubico" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'

j***@td:~$ cat /etc/issue
Debian GNU/Linux 9 \n \l
```

Let me know if you have any additional questions.

**Comment by dagheyman** [comment]
Thanks for the report!

Supporting Debian in the Ubuntu PPA is not on the roadmap, my recommendation would be to use the AppImage (found here: https://developers.yubico.com/yubikey-manager-qt/Releases/) or try to get it packaged for Debian directly (see https://salsa.debian.org/auth-team).
