### ISSUE TITLE
[Windows] Yubikey Manager + ykman: usb.core.USBError: [Errno None] Other error

### ISSUE THREAD

**Issue by OomJan** [Yubico/yubikey-manager-qt#245]
Good Day!

OS: Windows 10 Pro 2004 x64 de-DE, Windows 10 Pro 1909 x64 de-DE
Key: YubiKey 5 NFC
YubiKey Manager: 1.1.3, 1.1.5 (both x86 and x64)

When using the Yubikey Manager GUI it will only display "Insert your YubiKey" with no further information when the YubiKey 5 NFC is plugged in. The "ykman" lists the key as reader but will not list the serial number. How can I use my key?

```
C:\Program Files\Yubico\YubiKey Manager>ykman list -r
Yubico YubiKey OTP+FIDO+CCID 0
```

```
C:\Program Files\Yubico\YubiKey Manager>ykman list -s
`"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/cli.py\", line 12, in run\n    return main()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 274, in main\n    cli(obj={})\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 228, in list_keys\n    descriptors = get_descriptors()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 152, in get_descriptors\n    return list(_gen_descriptors())\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 142, in _gen_descriptors\n    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\core.py\", line 1246, in device_iter\n    for dev in backend.enumerate_devices():\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 717, in enumerate_devices\n    return _DevIterator(self.ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 629, in __init__\n    self.num_devs = _check(_lib.libusb_get_device_list(\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 595, in _check\n    raise USBError(_strerror(ret), ret, _libusb_errno[ret])\n\nusb.core.USBError: [Errno None] Other error\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 274, in main
    cli(obj={})

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 782, in main
    rv = self.invoke(ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 228, in list_keys
    descriptors = get_descriptors()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 152, in get_descriptors
    return list(_gen_descriptors())

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 142, in _gen_descriptors
    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\core.py", line 1246, in device_iter
    for dev in backend.enumerate_devices():

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 717, in enumerate_devices
    return _DevIterator(self.ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 629, in __init__
    self.num_devs = _check(_lib.libusb_get_device_list(

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

usb.core.USBError: [Errno None] Other error
```

**Comment by fdennis** [comment]
This seems strange. Could you please run `ykman --version` and post the output here?

**Comment by fdennis** [comment]
Could you try running `ykman --log-level DEBUG list -s` and post here?

**Comment by OomJan** [comment]
```
C:\Program Files\Yubico\YubiKey Manager>ykman --log-level DEBUG list -s
2020-09-04T15:12:15+0200 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/cli.py\", line 12, in run\n    return main()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 274, in main\n    cli(obj={})\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 228, in list_keys\n    descriptors = get_descriptors()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 152, in get_descriptors\n    return list(_gen_descriptors())\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 142, in _gen_descriptors\n    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\core.py\", line 1246, in device_iter\n    for dev in backend.enumerate_devices():\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 717, in enumerate_devices\n    return _DevIterator(self.ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 629, in __init__\n    self.num_devs = _check(_lib.libusb_get_device_list(\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 595, in _check\n    raise USBError(_strerror(ret), ret, _libusb_errno[ret])\n\nusb.core.USBError: [Errno None] Other error\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 274, in main
    cli(obj={})

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 782, in main
    rv = self.invoke(ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 228, in list_keys
    descriptors = get_descriptors()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 152, in get_descriptors
    return list(_gen_descriptors())

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 142, in _gen_descriptors
    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\core.py", line 1246, in device_iter
    for dev in backend.enumerate_devices():

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 717, in enumerate_devices
    return _DevIterator(self.ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 629, in __init__
    self.num_devs = _check(_lib.libusb_get_device_list(

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

usb.core.USBError: [Errno None] Other error
```

**Comment by fdennis** [comment]
Can you try other ykman commands? Such as `ykman info` and `ykman list` for example. Do you get the same error with them?

**Comment by OomJan** [comment]
I'm on leave for the next two weeks, I will provide the data on 21.09.

**Comment by OomJan** [comment]
As promised here are some more commands:

I have in the mean time tested this on my private computer and there it works. There is not much difference in both systems except for the anti-virus software (Company: FortiNet, Private: Windows Defender).

```
C:\Program Files\Yubico\YubiKey Manager>ykman --log-level DEBUG info
2020-09-21T09:29:18+0200 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/cli.py\", line 12, in run\n    return main()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 274, in main\n    cli(obj={})\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\info.py\", line 137, in info\n    dev = ctx.obj['dev']\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\util.py\", line 128, in __getitem__\n    self.resolve()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\util.py\", line 125, in resolve\n    self._objects[k] = f()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 195, in resolve_device\n    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 120, in _run_cmd_for_single\n    descriptors = get_descriptors()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 152, in get_descriptors\n    return list(_gen_descriptors())\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 142, in _gen_descriptors\n    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\core.py\", line 1246, in device_iter\n    for dev in backend.enumerate_devices():\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 717, in enumerate_devices\n    return _DevIterator(self.ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 629, in __init__\n    self.num_devs = _check(_lib.libusb_get_device_list(\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 595, in _check\n    raise USBError(_strerror(ret), ret, _libusb_errno[ret])\n\nusb.core.USBError: [Errno None] Other error\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 274, in main
    cli(obj={})

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 782, in main
    rv = self.invoke(ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\info.py", line 137, in info
    dev = ctx.obj['dev']

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\util.py", line 128, in __getitem__
    self.resolve()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\util.py", line 125, in resolve
    self._objects[k] = f()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 195, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 120, in _run_cmd_for_single
    descriptors = get_descriptors()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 152, in get_descriptors
    return list(_gen_descriptors())

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 142, in _gen_descriptors
    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\core.py", line 1246, in device_iter
    for dev in backend.enumerate_devices():

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 717, in enumerate_devices
    return _DevIterator(self.ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 629, in __init__
    self.num_devs = _check(_lib.libusb_get_device_list(

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

usb.core.USBError: [Errno None] Other error
```

```
C:\Program Files\Yubico\YubiKey Manager>ykman --log-level DEBUG list
2020-09-21T09:29:24+0200 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/cli.py\", line 12, in run\n    return main()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 274, in main\n    cli(obj={})\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 228, in list_keys\n    descriptors = get_descriptors()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 152, in get_descriptors\n    return list(_gen_descriptors())\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 142, in _gen_descriptors\n    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\core.py\", line 1246, in device_iter\n    for dev in backend.enumerate_devices():\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 717, in enumerate_devices\n    return _DevIterator(self.ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 629, in __init__\n    self.num_devs = _check(_lib.libusb_get_device_list(\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 595, in _check\n    raise USBError(_strerror(ret), ret, _libusb_errno[ret])\n\nusb.core.USBError: [Errno None] Other error\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 274, in main
    cli(obj={})

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 782, in main
    rv = self.invoke(ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 228, in list_keys
    descriptors = get_descriptors()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 152, in get_descriptors
    return list(_gen_descriptors())

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 142, in _gen_descriptors
    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\core.py", line 1246, in device_iter
    for dev in backend.enumerate_devices():

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 717, in enumerate_devices
    return _DevIterator(self.ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 629, in __init__
    self.num_devs = _check(_lib.libusb_get_device_list(

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

usb.core.USBError: [Errno None] Other error
```

```
C:\Program Files\Yubico\YubiKey Manager>ykman --log-level DEBUG otp yubiotp 1 --serial-public-id
2020-09-21T09:30:45+0200 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/cli.py\", line 12, in run\n    return main()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 274, in main\n    cli(obj={})\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 782, in main\n    rv = self.invoke(ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\click\\decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\otp.py\", line 261, in yubiotp\n    dev = ctx.obj['dev']\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\util.py\", line 128, in __getitem__\n    self.resolve()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\util.py\", line 125, in resolve\n    self._objects[k] = f()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 195, in resolve_device\n    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\cli\\__main__.py\", line 120, in _run_cmd_for_single\n    descriptors = get_descriptors()\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 152, in get_descriptors\n    return list(_gen_descriptors())\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\ykman\\descriptor.py\", line 142, in _gen_descriptors\n    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\core.py\", line 1246, in device_iter\n    for dev in backend.enumerate_devices():\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 717, in enumerate_devices\n    return _DevIterator(self.ctx)\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 629, in __init__\n    self.num_devs = _check(_lib.libusb_get_device_list(\n\n  File \"C:\\Program Files\\Yubico\\YubiKey Manager\\pymodules\\usb\\backend\\libusb1.py\", line 595, in _check\n    raise USBError(_strerror(ret), ret, _libusb_errno[ret])\n\nusb.core.USBError: [Errno None] Other error\n"
qml: Return value of PyObject call is NULL: Traceback (most recent call last):

  File "qrc:///py/cli.py", line 12, in run
    return main()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 274, in main
    cli(obj={})

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 782, in main
    rv = self.invoke(ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\otp.py", line 261, in yubiotp
    dev = ctx.obj['dev']

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\util.py", line 128, in __getitem__
    self.resolve()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\util.py", line 125, in resolve
    self._objects[k] = f()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 195, in resolve_device
    dev = _run_cmd_for_single(ctx, subcmd.name, transports, reader)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\cli\__main__.py", line 120, in _run_cmd_for_single
    descriptors = get_descriptors()

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 152, in get_descriptors
    return list(_gen_descriptors())

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\ykman\descriptor.py", line 142, in _gen_descriptors
    for dev in usb.core.find(True, idVendor=0x1050, backend=backend):

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\core.py", line 1246, in device_iter
    for dev in backend.enumerate_devices():

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 717, in enumerate_devices
    return _DevIterator(self.ctx)

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 629, in __init__
    self.num_devs = _check(_lib.libusb_get_device_list(

  File "C:\Program Files\Yubico\YubiKey Manager\pymodules\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])

usb.core.USBError: [Errno None] Other error
```

**Comment by OomJan** [comment]
As per company policy the AV software may not be deactivated so I cannot test. Since I have a workaround to use my private PC to at least set up the keys, I can live with that for now.

Closing the ticket as "No fix - workaround".

**Comment by dainnilsson** [comment]
Alright, fully understandable! I hope the next major version solves your issue in any case!
