### ISSUE TITLE
does not recognize yubikey, "NameError: name 'yubikey' is not defined"

### ISSUE THREAD

**Issue by steven-omaha** [Yubico/yubikey-manager-qt#282]
- version 1.2.1
- Arch Linux

```
$ ykman-gui

Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 26, in <module>\n    from ykman import connect_to_device, scan_devices, get_name\n\nImportError: cannot import name 'connect_to_device' from 'ykman' (/usr/lib/python3.9/site-packages/ykman/__init__.py)\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 26, in <module>
    from ykman import connect_to_device, scan_devices, get_name

ImportError: cannot import name 'connect_to_device' from 'ykman' (/usr/lib/python3.9/site-packages/ykman/__init__.py)
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined

```

The name error is repeated forever.

GUI is stuck in "Insert your YubiKey".

**Comment by dainnilsson** [comment]
yubikey-manager-qt 1.2 and above require `yubikey-manager >= 4.0`. Based on this output and your other issue I believe you're running yubikey-manager 3.x. It looks like the Arch package for yubikey-manager needs to be updated. Yubico doesn't maintain that package, so you'll have to contact the Arch package maintainers.

**Comment by steven-omaha** [comment]
Thanks for quick reaction!
