### ISSUE TITLE
Management Key won't generate on M1.

### ISSUE THREAD

**Issue by sethf200** [Yubico/yubikey-manager-qt#316]
- YubiKey Manager (ykman) version: 1.2.4
- How was it installed?: Downloaded from yubico.com.
- Operating system and version: MacOS Monterey 12.0.1
- YubiKey model and version: YubiKey5C 5.2.7
- Bug description summary:
Cannot create new Management Key in Yubikey Manager.

I was trying to create a new Management key, it kept giving me an error so I dug deeper and it looks like it's an architecture issue. It's saying a file is for arm64 when it needs x86_64. I'll put the logs below.

2021-12-18T19:52:13-0500 ERROR [yubikey.wrapped:80] Uncaught exception
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 68, in wrapped
    return f(*args, **kwargs)
  File "qrc:///py/yubikey.py", line 624, in piv_change_mgm_key
    auth_failed = self._piv_ensure_authenticated(
  File "qrc:///py/yubikey.py", line 797, in _piv_ensure_authenticated
    session.authenticate(
  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yubikit/piv.py", line 493, in authenticate
    backend = default_backend()
  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Applications/YubiKey Manager.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/username/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Users/username/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/_cffi_backend.cpython-39-darwin.so' (no such file)
qml: Unmapped error: null dlopen(/Users/username/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Users/username/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/_cffi_backend.cpython-39-darwin.so' (no such file)

**Comment by fdennis** [comment]
Hi,
It looks like it is not using the bundled Python. You can see this from the path `/Users/username/Library/Python/3.9`, which is your own local Python. I am not sure what has caused this. Perhaps there is a PYTHONPATH or PYTHONHOME variable set?

**Comment by apburgess** [comment]
Ok, I've tried that, I'm not sure if I set the variables correctly but it keeps reaching out to the system installation for cryptography -- is it possible this is because there isn't a copy included in the app bundle (that I can see -- not a python expert).

![Screenshot 2022-04-29 at 11 49 28](https://user-images.githubusercontent.com/3983065/165930717-235e22fe-82be-41f6-8e81-c123df795636.png)

I was trying

`PYTHONHOME=/Applications/YubiKey\ Manager.app/Contents/Frameworks/Python.framework/Versions/3.9`
