### ISSUE TITLE
Applications>PIV tab throws `qml: Unmapped error: null __enter__` if pcscd service not running.

### ISSUE THREAD

**Issue by ipaqmaster** [Yubico/yubikey-manager-qt#343]
- YubiKey Manager version: `1.2.5`
- How was it installed?: `pacman -S yubikey-manager-qt`
- Operating system and version: Archlinux, Linux 6.2.7-arch1-1
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: If you've just installed this package and have not touched the pcscd service on your machine ever, visiting the Applications > PIV tab results in this GUI experience:

![image](https://user-images.githubusercontent.com/26422790/226489460-65b7736d-cc47-4a11-ac30-47fed880ffbd.png)

Steps to reproduce
---

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Go to the PIV tab.

Expected result
---

[What did you expect to happen when you did the above?]

PIV options.

Actual results

---

[What actually happened?]

Vague general Exception error which doesn't hint at the real and simple solution in any way. Only discovered solution through some online searching.

Other info
---

[Anything else you would like to add?]

**Comment by ipaqmaster** [comment]
Oh, I thought I pasted the stack trace in here already. I've stopped the pcscd service now and got this fresh stacktrace to paste:

```
PC/SC not available. Smart card (CCID) protocols will not function.
Unable to list devices for connection
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/device.py", line 287, in list_all_devices
    for dev in _CONNECTION_LIST_MAPPING[connection_type]():
  File "/usr/lib/python3.10/site-packages/ykman/device.py", line 71, in inner
    return f()
  File "/usr/lib/python3.10/site-packages/ykman/device.py", line 88, in list_ccid_devices
    return _list_ccid_devices()
  File "/usr/lib/python3.10/site-packages/ykman/pcsc/__init__.py", line 169, in list_devices
    for reader in list_readers():
  File "/usr/lib/python3.10/site-packages/ykman/pcsc/__init__.py", line 157, in list_readers
    return System.readers()
  File "/usr/lib/python3.10/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/usr/lib/python3.10/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/usr/lib/python3.10/site-packages/smartcard/pcsc/PCSCReader.py", line 109, in readers
    hcontext = PCSCContext().getContext()
  File "/usr/lib/python3.10/site-packages/smartcard/pcsc/PCSCContext.py", line 56, in __init__
    self.renewContext()
  File "/usr/lib/python3.10/site-packages/smartcard/pcsc/PCSCContext.py", line 70, in renewContext
    PCSCContext.instance = PCSCContext.__PCSCContextSingleton()
  File "/usr/lib/python3.10/site-packages/smartcard/pcsc/PCSCContext.py", line 40, in __init__
    raise EstablishContextException(hresult)
smartcard.pcsc.PCSCExceptions.EstablishContextException: Failed to establish context: Service not available. (0x8010001D)
Uncaught exception
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 78, in wrapped
    return f(*args, **kwargs)
  File "qrc:///py/yubikey.py", line 300, in refresh_piv
    with self._open_device([SmartCardConnection]) as conn:
AttributeError: __enter__
qml: Unmapped error: null __enter__
```

My original provided screeenshot happened again exactly the same.

> I am not able to reproduce on Ubuntu

Probably because you did not stop pcscd -- but it is also a testament that the socket may have automatically started it on that distro but doesn't do that on Archlinux. Here it does not start it on its own despite the existence of pcscd.socket --- but also, the GUI error does not accurately describe the issue to the user so it can be fixed manually.

**Comment by ipaqmaster** [comment]
To clarify, this seems to be a problem on fresh installs. Ever since I started pcscd myself, the socket seems to be doing its job correctly? But it still doesn't address that the GUI error it throws doesn't help troubleshoot / self-resolve in the slightest.

**Comment by fdennis** [comment]
Thanks for the log!

> Probably because you did not stop pcscd

I should have been more clear. I meant to say that I cannot reproduce the same error message that you get (`Unmapped error: null __enter__`) on my Ubuntu machine. I am stopping pcscd but when I press PIV I get the correct error message, which basically explains that it cannot connect to the YubiKey. Perhaps this is not an issue on Ubuntu but is an issue on Arch and/or other distros. I do agree that the GUI error is not that helpful. We will look into this. Thank you!

**Comment by ipaqmaster** [comment]
I appreciate your understanding of the issue and a desire to at least make it more clear for the UI.

Thanks
