### ISSUE TITLE
YubiKeys not recognized

### ISSUE THREAD

**Issue by auroraanna** [Yubico/yubikey-manager-qt#366]
- YubiKey Manager version: 1.2.5
- How was it installed?: from nixpkgs
- Operating system and version: NixOS unstable with Linux 6.6.52
- YubiKey model and version: YubiKey 5C NFC firmware version 5.4.3
- Bug description summary: The program does does not recognize any of my two YubiKeys

Steps to reproduce
---
Execute ykman-gui, plug in YubiKey.

Expected result
---
The application allows for configuration of the YubiKey.

Actual results
---
"Insert your YubiKey", cli error message (is repeated):
```
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
```

**Comment by taivlam** [comment]
I think I noticed this at least 1-2 months ago, but only recently did I try to look deeper into this.

### Details
* YubiKey Manager version: 1.2.5
* How was it installed?
    - From `pacman`
* Operating system and version: Manjaro Unstable (latest updates) with Linux kernel 6.10.14-1
* YubiKey model and version
    - YubiKey 5 NFC, firmware version 5.4.3
    - YubiKey 5C, firmware version 5.4.3
    - YubiKey 5C NFC, firmware version 5.7.1
    - YubiKey 5 Nano, firmware version 5.7.1
* Bug description summary
    - YubiKey Manager GUI program does does not recognize any of my YubiKeys.
    - However, running `$ ykman info` in a terminal emulator works, thus this indicates that my machine is able to recognize my YubiKey devices via the CLI, but not via the GUI.

### Logs

This is the stdout from launching the YubiKey manager app in the terminal (and I indicate in the comment what sections seem to endlessly repeat until the program is closed):
```
$ ykman-gui
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 53, in <module>\n    from ykman.otp import (\n\nImportError: cannot import name '_PrepareUploadFailed' from 'ykman.otp' (/usr/lib/python3.12/site-packages/ykman/otp.py)\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 53, in <module>
    from ykman.otp import (

ImportError: cannot import name '_PrepareUploadFailed' from 'ykman.otp' (/usr/lib/python3.12/site-packages/ykman/otp.py)
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: qrc:/qml/YubiKey.qml:208: TypeError: Cannot read property 'success' of undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: Function not found: 'yubikey.controller.refresh' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
# this last section will repeat until `ykman-gui` is closed
```

**Comment by taivlam** [comment]
This contrasts with the latest stable of Pop!\_OS (22.04 LTS, with latest system updates), which uses version 1.2.4 of YubiKey Manager, and still manages to open fine with no issues.  All that I see when I launch the GUI application via a terminal emulator is the following (including after closing YubiKey Manager):
```
$ ykman-gui 
Got library name:  "/usr/lib/x86_64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
```

**Comment by tony1661** [comment]
I am having the same issue on Linux Mint 22

**Comment by aryklein** [comment]
Same issue in Archlinux: `yubikey-manager-qt-1.2.5-2`

**Comment by rahra** [comment]
Same on Ubuntu 24.04, yubikey-manager-qt 1.2.5-1build2.
