### ISSUE TITLE
No YubiKey detected

### ISSUE THREAD

**Issue by jethrogb** [Yubico/yubikey-manager-qt#48]
When launching `ykman-gui`, I get the following message: "No YubiKey detected". The command line client works fine:

```
$ ykman list
YubiKey 4 [OTP+FIDO+CCID] Serial: 6441777
```

Error output:
```
$ ykman-gui
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2144, in _normalize_cached\n    return _cache[filename]\n\nKeyError: 'qrc:///py'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 16, in <module>\n    from cryptography import x509\n\n  File \"/usr/lib/python3/dist-packages/cryptography/x509/__init__.py\", line 7, in <module>\n    from cryptography.x509.base import (\n\n  File \"/usr/lib/python3/dist-packages/cryptography/x509/base.py\", line 14, in <module>\n    from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa\n\n  File \"/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py\", line 14, in <module>\n    from cryptography.hazmat.backends.interfaces import RSABackend\n\n  File \"/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py\", line 7, in <module>\n    import pkg_resources\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2927, in <module>\n    @_call_aside\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2913, in _call_aside\n    f(*args, **kwargs)\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2952, in _initialize_master_working_set\n    add_activation_listener(lambda dist: dist.activate())\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 956, in subscribe\n    callback(dist)\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2952, in <lambda>\n    add_activation_listener(lambda dist: dist.activate())\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2510, in activate\n    self.insert_on(path, replace=True)\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2596, in insert_on\n    npath= [(p and _normalize_cached(p) or p) for p in path]\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2596, in <listcomp>\n    npath= [(p and _normalize_cached(p) or p) for p in path]\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2146, in _normalize_cached\n    _cache[filename] = result = normalize_path(filename)\n\n  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 2140, in normalize_path\n    return os.path.normcase(os.path.realpath(filename))\n\n  File \"/usr/lib/python3.5/posixpath.py\", line 373, in realpath\n    return abspath(path)\n\n  File \"/usr/lib/python3.5/posixpath.py\", line 361, in abspath\n    cwd = os.getcwd()\n\nFileNotFoundError: [Errno 2] No such file or directory\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2144, in _normalize_cached
    return _cache[filename]

KeyError: 'qrc:///py'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 16, in <module>
    from cryptography import x509

  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (

  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 14, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2510, in activate
    self.insert_on(path, replace=True)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2596, in insert_on
    npath= [(p and _normalize_cached(p) or p) for p in path]

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2596, in <listcomp>
    npath= [(p and _normalize_cached(p) or p) for p in path]

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2146, in _normalize_cached
    _cache[filename] = result = normalize_path(filename)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2140, in normalize_path
    return os.path.normcase(os.path.realpath(filename))

  File "/usr/lib/python3.5/posixpath.py", line 373, in realpath
    return abspath(path)

  File "/usr/lib/python3.5/posixpath.py", line 361, in abspath
    cwd = os.getcwd()

FileNotFoundError: [Errno 2] No such file or directory
```

I have the exact same issue with `yubioath-desktop`.

I'm on Ubuntu 16.04 and installed everything through the PPA:
```
$ dpkg -l|grep yubi
ii  libyubikey0                                   1.13-1                                       amd64        Yubikey OTP handling library runtime
ii  python3-yubikey-manager                       0.7.0~ppa1~xenial1                           all          Python 3 library for configuring a YubiKey
ii  yubikey-manager                               0.7.0~ppa1~xenial1                           all          Python library and command line tool for configuring a YubiKey
ii  yubikey-manager-qt                            0.5.1~ppa1~xenial1                           amd64        Graphical application for configuring a YubiKey
ii  yubioath-desktop                              4.3.4~ppa1~xenial1                           amd64        Graphical interface for displaying OATH codes with a Yubikey
```

**Comment by dagheyman** [comment]
Thanks for the report.

However, on a clean Ubuntu 16.04 installation with the exact same packages installed, I'm unable to reproduce this. You seem to have an issue with how PyOtherSide / Qt loads the yubikey-manager library, but since I can't reproduce it, it is hard to debug..

**Comment by jethrogb** [comment]
Apparently fixed itself after a reboot...
