### ISSUE TITLE
yubikey-manager-qt-0.5.2.tar.gz is missing VERSION file

### ISSUE THREAD

**Issue by gktrk** [Yubico/yubikey-manager-qt#54]
The tarball is missing the file `VERSION`, triggering a git repo search in `compute_version.py` and effectively failing to determine the version as follows:

```
Traceback (most recent call last):
  File "../compute-version.py", line 112, in <module>
    print(compute_version(tag_prefix=args.tag_prefix))
  File "../compute-version.py", line 82, in compute_version
    raise ChildProcessError(git_result.stderr)  # noqa: F821
ChildProcessError: fatal: not a git repository (or any parent up to mount point /var/tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Project MESSAGE: Version of this build:
```

**Comment by dagheyman** [comment]
Thanks for the report, we'll look into this.

**Comment by dagheyman** [comment]
The 1.0.0 release should have the VERSION file included.
